### ISSUE TITLE
Compilation problems on a computer with AMD processor

### ISSUE THREAD

**Issue by svkazakov** [nanoporetech/scrappie#3] opened 2017-06-23 14:04 UTC
Hello, 
I just want to test your tool, but I've got a compilation error:

...
Scanning dependencies of target scrappie_objects
[  5%] Building C object CMakeFiles/scrappie_objects.dir/src/decode.c.o
In file included from /usr/lib/gcc/x86_64-linux-gnu/5/include/immintrin.h:37:0,
                 from /home/svkazakov/work/genome/nanopore/scrappie/src/scrappie_matrix.h:4,
                 from /home/svkazakov/work/genome/nanopore/scrappie/src/decode.h:5,
                 from /home/svkazakov/work/genome/nanopore/scrappie/src/decode.c:5:
/home/svkazakov/work/genome/nanopore/scrappie/src/decode.c: In function ‘decode_transducer’:
/usr/lib/gcc/x86_64-linux-gnu/5/include/smmintrin.h:326:1: **error:** inlining failed in call to always_inline ‘_mm_mullo_epi32’: target specific option mismatch
 _mm_mullo_epi32 (__m128i __X, __m128i __Y)
 ^
/home/svkazakov/work/genome/nanopore/scrappie/src/decode.c:84:22: **error:** called from here
    itmp->data.v[i] = _mm_add_epi32(
...
- - -

A full log is here: [log.txt](https://github.com/nanoporetech/scrappie/files/1097978/log.txt)

I also found [here](https://stackoverflow.com/questions/43128698/inlining-failed-in-call-to-always-inline-mm-mullo-epi32-target-specific-opti) that the problem can be solved by adding "-msse4.1" compiler option. But I have an AMD processor without SSE4.1 support, only SSE4A. With "-msse4a" it doesn't compile too.

processor:
vendor_id          : AuthenticAMD
model name      : AMD Phenom(tm) II X6 1090T Processor
OS: Linux 4.4.0-77-generic #98-Ubuntu SMP Wed Apr 26 08:34:02 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
gcc (Ubuntu 5.4.0-6ubuntu1~16.04.4) 5.4.0 20160609

Thanks,
Sergey

**Comment by tmassingham-ont** [comment] 2017-06-28 10:21
Hello.  Thanks for your detailed analysis, you are exactly right.  The problem is that one of the routine uses SSE4.1 intrinsics and these are not support on all processors.

We initially wrote this routine this way for simplicity but I have pushed a work-around to the branch 'staging' that I think will sort the problem for you.  Would you be able to test please?

Thanks,

TimM.

**Comment by wyzhangMPI** [comment] 2017-07-03 20:13
Hi, I tried to install your program with make, and found the following problem:

[  7%] Building C object CMakeFiles/scrappie_objects.dir/src/decode.c.o
[ 14%] Building C object CMakeFiles/scrappie_objects.dir/src/nnfeatures.c.o
[ 21%] Building C object CMakeFiles/scrappie_objects.dir/src/layers.c.o
[ 28%] Building C object CMakeFiles/scrappie_objects.dir/src/util.c.o
[ 35%] Building C object CMakeFiles/scrappie_objects.dir/src/networks.c.o
[ 42%] Building C object CMakeFiles/scrappie_objects.dir/src/scrappie_matrix.c.o
[ 42%] Built target scrappie_objects
Linking C static library libscrappie.a
[ 42%] Built target scrappie_static
[ 50%] Building C object CMakeFiles/scrappie.dir/src/scrappie.c.o
[ 57%] Building C object CMakeFiles/scrappie.dir/src/scrappie_raw.c.o
[ 64%] Building C object CMakeFiles/scrappie.dir/src/scrappie_events.c.o
[ 71%] Building C object CMakeFiles/scrappie.dir/src/scrappie_subcommands.c.o
[ 78%] Building C object CMakeFiles/scrappie.dir/src/scrappie_help.c.o
[ 85%] Building C object CMakeFiles/scrappie.dir/src/fast5_interface.c.o
Linking C executable scrappie
libscrappie.a(scrappie_matrix.c.o): In function `affine_map':
scrappie_matrix.c:(.text+0x9ab): undefined reference to `cblas_sgemm'
libscrappie.a(scrappie_matrix.c.o): In function `affine_map2':
scrappie_matrix.c:(.text+0xac0): undefined reference to `cblas_sgemm'
scrappie_matrix.c:(.text+0xb2d): undefined reference to `cblas_sgemm'
libscrappie.a(layers.c.o): In function `Convolution':
layers.c:(.text+0x495): undefined reference to `cblas_sgemv'
layers.c:(.text+0x5c7): undefined reference to `cblas_sgemm'
layers.c:(.text+0x6fe): undefined reference to `cblas_sgemv'
libscrappie.a(layers.c.o): In function `gru_step':
layers.c:(.text+0xe08): undefined reference to `cblas_sgemv'
layers.c:(.text+0xe57): undefined reference to `cblas_sgemv'
layers.c:(.text+0x103c): undefined reference to `cblas_sgemv'
layers.c:(.text+0x1200): undefined reference to `cblas_sgemv'
libscrappie.a(layers.c.o):layers.c:(.text+0x16cb): more undefined references to `cblas_sgemv' follow
collect2: error: ld returned 1 exit status
make[2]: *** [scrappie] Error 1
make[1]: *** [CMakeFiles/scrappie.dir/all] Error 2
make: *** [all] Error 2

Any idea on what is happending here?
Thanks!

Wenyu

**Comment by tmassingham-ont** [comment] 2017-07-04 08:08
Scrappie requires the cblas library to run and this provided by the recommended installation of the OpenBLAS package.  If cblas is provided by a different library, you will probably need to explicitly link against it.  Without knowing your setup, I can't give an exact recommendation but, in most cases, I would expected altering the lines
```
target_link_libraries (scrappie scrappie_static ${BLAS} ${HDF5} m)
...
target_link_libraries(scrappie_unittest scrappie_static ${BLAS} ${HDF5} m cunit)
```
in CmakeLists.txt to
```
target_link_libraries (scrappie scrappie_static cblas ${BLAS} ${HDF5} m)
...
target_link_libraries(scrappie_unittest scrappie_static cblas ${BLAS} ${HDF5} m cunit)
```
to suffice.

Hope this helps,

TimM.

**Comment by svkazakov** [comment] 2017-07-04 13:59
Hello Tim, 
Thank you for your fast response!

Later I have found a server in our lab with AMD processor and SSE4.1 support, so I tested scrappie on it first.
Now I also tested scrappie on my own computer (AMD without SSE4.1) using branch 'staging'. The code compiled well, and the build also worked well.
I have used two small datasets with R9 and R9.4 nanopore reads to run scrappie. 

Results seem to be a little bit different: nucleotide sequences produced by scrappie differ from each other - difference in length is usually within 1%. The identity of its mapping is the same for ~90% reads.
Running time of scrappie on AMD without SSE4.1 is greater by 15-21% than time on AMD with SSE4.1 (I run it in one thread for every read separately).

Such difference may be explained by different processors (AMD Phenom II X6 1090T vs. AMD Opteron 6234) or different OS (Ubuntu xenial 16.04 LTS vs. Ubuntu trusty 14.04 LTS).


Sergey.

**Comment by wyzhangMPI** [comment] 2017-07-04 14:23
Hi Tim,
    Thanks for the quick response.
    our computation grid setup is : 
Linux version 3.10.0-514.2.2.el7.x86_64 (builder@kbuilder.dev.centos.org) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-11) (GCC) ) #1 SMP Tue Dec 6 23:06:41 UTC 2016.
Any suggestions based on this set-up?

Thanks!

**Comment by tmassingham-ont** [comment] 2017-07-10 11:04
@wyzhangMPI 
Sorry, I have no experience with that platform and so can't provide any suggestions.  If you find a solution, please come back and share it.
 
Scrappie is provided for research only and is not officially supported by ONT.  If you need support, please consider our production 'Albacore' basecaller instead.

**Comment by tmassingham-ont** [comment] 2017-07-10 11:09
@svkazakov 
I think it is a processor or compiler difference.  If I compile with and without the SSE4.1 support, then run on the same machine, I get the same answer for my test set of reads.  Without being able to reproduce the difference, it is difficult to make any further progress so I'm going to close the issue but try to remember it next time I'm refactoring the code.

TimM.

**Closed by tmassingham-ont** 2017-07-10 11:09 UTC
